const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //CHANGE LANGUAGE
    CHANGE_LANGUAGES: 'CHANGE_LANGUAGES',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER: 'FETCH_GENDER',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',
    FETCH_ROLE: 'FETCH_ROLE',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',
    FETCH_POSITION: 'FETCH_POSITION',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',
    
    FETCH_ALL_USER: 'FETCH_ALL_USER',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: 'FETCH_ALL_USER_FAIL',

    DELTE_USER: 'DELTE_USER',
    DELTE_USER_SUCCESS: 'DELTE_USER_SUCCESS',
    DELTE_USER_FAIL: 'DELTE_USER_FAIL',

    EDIT_USER: 'EDIT_USER',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',


    //doctor
    FETCH_DOCTOR: 'FETCH_DOCTOR',
    FETCH_DOCTOR_SUCCESS: 'FETCH_DOCTOR_SUCCESS',
    FETCH_DOCTOR_FAIL: 'FETCH_DOCTOR_FAIL',

    FETCH_ALL_DOCTOR: 'FETCH_ALL_DOCTOR',
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIL: 'FETCH_ALL_DOCTOR_FAIL',

    CREATE_DETAIL_DOCTOR: ' CREATE_DETAIL_DOCTOR',
    CREATE_DETAIL_DOCTOR_SUCCESS: ' CREATE_DETAIL_DOCTOR_SUCCESS',
    CREATE_DETAIL_DOCTOR_FAIL: 'CREATE_DETAIL_DOCTOR_FAIL',

    FETCH_SCHEDULE_HOURS: 'FETCH_SCHEDULE_HOURS',
    FETCH_SCHEDULE_HOURS_SUCCESS: 'FETCH_SCHEDULE_HOURS_SUCCESS',
    FETCH_SCHEDULE_HOURS_FAIL: 'FETCH_SCHEDULE_HOURS_FAIL',

    FETCH_ALL_INFO_DOCTOR: 'FETCH_ALL_INFO_DOCTOR',
    FETCH_ALL_INFO_DOCTOR_SUCCESS: 'FETCH_ALL_INFO_DOCTOR_SUCCESS',
    FETCH_ALL_INFO_DOCTOR_FAIL: 'FETCH_ALL_INFO_DOCTOR_FAIL',

    //specialty
    FETCH_SPECIALTY: 'FETCH_SPECIALTY',
    FETCH_SPECIALTY_SUCCESS: 'FETCH_SPECIALTY_SUCCESS',
    FETCH_SPECIALTY_FAIL: 'FETCH_SPECIALTY_FAIL',

    //clinic

    FETCH_CLINIC: 'FETCH_CLINIC',
    FETCH_CLINIC_SUCCESS: 'FETCH_CLINIC_SUCCESS',
    FETCH_CLINIC_FAIL: 'FETCH_CLINIC_FAIL',
})

export default actionTypes;